openapi: 3.0.0
info:
  title: EL-PRO API
  description: EL-PRO API.
  version: 1.0.0
servers:
  - url: 'https://127.0.0.1/el-pro/api/0.0.1'
    description: Back end server
paths:

  '/certifies_info/{user_id}':
    get:
      tags:
        - Certifies
      summary: 部下の資格情報情報獲得
      parameters: 
        - name: user_id
          in: path
          description: administrator_ID
          required: true
          schema:
            type: string

        - name: time_scale
          in: path
          description: selected time
          required: true
          schema:
            type: string

      responses:
        '200':
          description: 部下の資格情報を獲得成功
          content:
            application/json:
              schema:
                type: string
                format: json
                example:
                  result:
                    code: USERINFOGET200
                    message: Success
                  certifies:
                    certificate_name: '基本情報試験'
                    keeper_num: '2'
                    scheduled_num: '4'
        '404':
          description: USER_ID存在しない。
          content:
            application/json:
              schema:
                type: string
                format: json
                example:
                  result:
                    code: USERINFOGET404
                    message: USER Not Found.
        '500':
          description: 予期せぬエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'

  '/certifies_info/{name_search}':
      get:
        tags:
          - Certifies
        summary: 名前で部下の資格情報情報獲得
        parameters: 
          - name: user_id
            in: path
            description: administrator_ID
            required: true
            schema:
              type: string

          - name: time_scale
            in: path
            description: selected time
            required: true
            schema:
              type: string

          - name: input_name
            in: path
            description: inputted name
            required: true
            schema:
              type: string

        responses:
          '200':
            description: 部下の資格情報を獲得成功
            content:
              application/json:
                schema:
                  type: string
                  format: json
                  example:
                    result:
                      code: USERINFOGET200
                      message: Success
                    certifies:
                      certificate_name: '基本情報試験'
                      keeper_num: '2'
                      scheduled_num: '4'
          '404':
            description: この名前は存在しない。
            content:
              application/json:
                schema:
                  type: string
                  format: json
                  example:
                    result:
                      code: USERINFOGET404
                      message: USER Not Found.
          '500':
            description: 予期せぬエラー
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Result'

components:
  schemas:
    Result:
      type: object
      required:
        - code
        - massage
      properties:
        result:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
          example:
            code: 'XXX999(XX:機能分類コード)'
            message: unexpected error.